apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: dev
data:
  NODE_ENV: production
  PORT: "3000"
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: labdb
  APP_VERSION: "1.0.0"