apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lab-pool
  namespace: infra
spec:
  addresses:
  - 217.160.55.68/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lab-l2
  namespace: infra
spec:
  ipAddressPools:
  - lab-pool